# This is a basic workflow to help you get started with Actions

name: Deploy to AWS

on:
  push:
    branches: master


jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
      - uses: actions/setup-node@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
            npm install
            npm run build
          
 
          
